theme: jekyll-theme-minimal

title: "Yue Zhao"
description: "PhD student\nDelft University of Technology."

show_photo: "true"
photo_src: http://www.wis.ewi.tudelft.nl/fileadmin/wis/images/yue-zhao-c3.jpg