theme: jekyll-theme-minimal

title: "Yue Zhao"
description: "PhD student at the Web Information Systems Group of the Faculty of Engineering, Mathematics and Computer Science (EEMCS/EWI), Delft University of Technology."

show_photo: "true"
photo_src: http://www.wis.ewi.tudelft.nl/fileadmin/wis/images/yue-zhao-c3.jpg